language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master
    - /^rfc.*$/

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

env:
  - WP_VERSION=latest WP_MULTISITE=0

matrix:
  include:
    - php: 5.3
      env: WP_VERSION=latest WP_MULTISITE=1
    - php: 5.6
      env: WP_VERSION=4.4 WP_MULTISITE=0
    - php: 5.6
      env: WP_VERSION=4.3 WP_MULTISITE=0
    - php: 5.6
      env: WP_VERSION=4.2 WP_MULTISITE=0

before_script:
  # - git clone https://github.com/woothemes/woocommerce ../woocommerce
  - wget https://github.com/woocommerce/woocommerce/archive/2.6.4.tar.gz && tar xf 2.6.4.tar.gz && cp -R woocommerce-2.6.4 ../woocommerce && rm -R woocommerce-2.6.4
  # - wget https://github.com/woothemes/woocommerce/archive/2.5.5.tar.gz && tar xf 2.5.5.tar.gz && cp -R woocommerce-2.5.5 ../woocommerce && rm -R woocommerce-2.5.5
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script: phpunit

notifications:
  email:
    recipients:
      - Developers@flagshipcompany.com
  slack:
    rooms:
      - flagshipcompany: secure: "YCoAjWUA7BYoII+2OtoGOEz9tdNb24H4WdiDZwl1R5sVh75omJosMTx4AQ1dBRO7qkGILd1qhR4EznRZ8/jv5pvip4GhbHP6nNtRAx7l3pCCBLHOJkvGtvuVonGDDmDvEX7mh8BggkZihSETc7pB2YxXJcn7sR8C2J5VzwhCIB2iHjl1Rb5Lm4Aq36B5mjhdW6N2rq/RRYQJzESSACNKKRPoKE8CDumjPh6nnN7aG/W1ZP9H+obDa5hFkJtf+d8Dhy/ZOkohzkDXiKl85FZldJ2X5iDAsWCXtasM9mtdpjpTFyc+ChwKP2R8JrgPxlN5q4dMC9Xo05NPyWOxsyi1/+urBS2BnyxTCt9Pruw3NqqpUX5IgGd+6+mdj6XDWCg2lbW7aN/NV0hNF0Bm+yLJis4qJy2BQGtskhNW8IjbvbWFFXtNP2aVW2x6yf5JlIL5DyI95lH5evB4KqH3LXkXeRk87h24HOxc5GgNtPgTKUDYdDea+ckaIMBWo0HufLEgtl8k/KNChtf4DbLP0YaVGPa9VPyj7fO4DNPPwjRBJYPXtlAnIMgjnM5a50WO/mroBcSLMKDAgCVwTr01ju0rHLstUzxmf6S53WhgnDEfA5sK8OE5xbRK31RCs+KyNDArY0BjHMFqhjG492ANOQ6BrBw8uTHhEYdMi90irVlbupA="

#Kb9L2QjrwcZh3uMYqMG7Qam6#developers